#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# program.sh - load a .sof onto the Arrow AXC3000 (Agilex 3) over JTAG,
#              from WSL2, through the board's on-board FTDI blaster that
#              usbipd-win has forwarded into this WSL distro.
#
#   usbipd (run on Windows, admin PowerShell) - do this first, every replug:
#       usbipd list
#       usbipd bind   --busid <b-p>          # once
#       usbipd attach --wsl --busid <b-p>
#
#   then, in WSL:
#       ./program.sh                         # program output_files/uart_test.sof
#       ./program.sh path/to/other.sof       # program a specific file
#       sudo ./program.sh --install-udev     # persistent perms + ftdi_sio unbind (once)
#       ./program.sh --check                 # set up + jtagconfig, don't program
#
# Env overrides:  QUARTUS_BIN=...  CABLE=<index>
# ---------------------------------------------------------------------------
set -uo pipefail

QUARTUS_BIN="${QUARTUS_BIN:-$HOME/altera_pro/26.1.1/quartus/bin}"
CABLE="${CABLE:-1}"
UDEV_RULE=/etc/udev/rules.d/51-usbblaster.rules

SUDO=""; [ "$(id -u)" -ne 0 ] && SUDO="sudo"

die()  { echo "ERROR: $*" >&2; exit 1; }
note() { echo ">> $*"; }

# --- find the on-board blaster in lsusb -------------------------------------
# matches FTDI (0403:*) or Intel/Altera USB-Blaster (09fb:*)
find_blaster() {
    lsusb | grep -iE 'ID (0403|09fb):' | head -n1
}

LINE="$(find_blaster)"
if [ -z "$LINE" ]; then
    echo "No USB-Blaster / FTDI device visible in lsusb." >&2
    echo "On Windows (admin PowerShell):" >&2
    echo "    usbipd list" >&2
    echo "    usbipd attach --wsl --busid <b-p>" >&2
    echo "then re-run this script." >&2
    exit 1
fi

VIDPID=$(sed -nE 's/.*ID ([0-9a-fA-F]{4}:[0-9a-fA-F]{4}).*/\1/p' <<<"$LINE")
VID=${VIDPID%:*}; PID=${VIDPID#*:}
BUS=$(awk '{print $2}' <<<"$LINE")
DEV=$(awk '{sub(/:/,"",$4); print $4}' <<<"$LINE")
note "blaster: $VIDPID  (bus $BUS dev $DEV)  [$LINE]"

# --- --install-udev : write a persistent rule and exit --------------------
if [ "${1:-}" = "--install-udev" ]; then
    [ -n "$SUDO" ] && die "run as root: sudo $0 --install-udev"
    cat > "$UDEV_RULE" <<EOF
# Arrow AXC3000 on-board blaster (auto-generated by program.sh)
SUBSYSTEM=="usb", ATTR{idVendor}=="$VID", ATTR{idProduct}=="$PID", MODE="0666"
SUBSYSTEM=="usb", ATTR{idVendor}=="09fb", MODE="0666"
# keep ftdi_sio off the JTAG interface (interface 0)
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="$VID", ATTRS{idProduct}=="$PID", \\
    ATTR{bInterfaceNumber}=="00", RUN+="/bin/sh -c 'echo \$kernel > /sys/bus/usb/drivers/ftdi_sio/unbind'"
EOF
    udevadm control --reload-rules
    udevadm trigger
    echo "wrote $UDEV_RULE - replug the board (usbipd attach again) to apply."
    exit 0
fi

# --- permissions on the raw USB node -------------------------------------
$SUDO chmod 666 "/dev/bus/usb/$BUS/$DEV" 2>/dev/null || true

# --- free interface 0 (JTAG) from the ftdi_sio serial driver ------------
if [ -d /sys/bus/usb/drivers/ftdi_sio ]; then
    for d in /sys/bus/usb/drivers/ftdi_sio/*:*.0; do
        [ -e "$d" ] || continue
        id=$(basename "$d")
        note "unbinding $id from ftdi_sio (JTAG channel)"
        echo -n "$id" | $SUDO tee /sys/bus/usb/drivers/ftdi_sio/unbind >/dev/null 2>&1 || true
    done
fi
# interface 1 stays as /dev/ttyUSBx - that is the UART for test_uart.py
ls -l /dev/ttyUSB* 2>/dev/null && note "^ UART channel for: python3 ../test_uart.py --board axc3000"

# --- (re)start jtagd ---------------------------------------------------
pkill -x jtagd 2>/dev/null || true
sleep 1
"$QUARTUS_BIN/jtagd" 2>/dev/null || true
sleep 1

# --- show the chain --------------------------------------------------
note "jtagconfig:"
"$QUARTUS_BIN/jtagconfig" || true

if [ "${1:-}" = "--check" ]; then
    exit 0
fi

# --- program --------------------------------------------------------
SOF="${1:-output_files/uart_test.sof}"
[ -f "$SOF" ] || die "sof not found: $SOF  (build it first)"

note "programming $SOF  (cable index $CABLE)"
exec "$QUARTUS_BIN/quartus_pgm" -c "$CABLE" -m jtag -o "p;$SOF"
