#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# program.sh - load a .sof onto the Arrow AXC3000 (Agilex 3) over JTAG,
#              from WSL2, through the board's on-board FTDI blaster that
#              usbipd-win has forwarded into this WSL distro.
#
#   usbipd (run on Windows, admin PowerShell) - do this first, every replug:
#       usbipd list
#       usbipd bind   --busid <b-p>          # once
#       usbipd attach --wsl --busid <b-p>
#
#   then, in WSL:
#       ./program.sh                         # program output_files/uart_test.sof
#       ./program.sh path/to/other.sof       # program a specific file
#       sudo ./program.sh --install-udev     # persistent perms + ftdi_sio unbind (once)
#       ./program.sh --check                 # set up + jtagconfig, don't program
#
# The board is found by its blaster's USB serial number, other Altera
# blasters (e.g. an Agilex 5 board) and FTDI boards attached are left alone.
#
# Env overrides:  QUARTUS_BIN=...  AXC3000_SERIAL=<usb serial>  CABLE=<jtagconfig cable name>
# ---------------------------------------------------------------------------
set -uo pipefail

QUARTUS_BIN="${QUARTUS_BIN:-$HOME/altera_pro/26.1.1/quartus/bin}"
AXC3000_SERIAL="${AXC3000_SERIAL:-TEA45543}"
UDEV_RULE=/etc/udev/rules.d/51-usbblaster.rules

SUDO=""; [ "$(id -u)" -ne 0 ] && SUDO="sudo"

die()  { echo "ERROR: $*" >&2; exit 1; }
note() { echo ">> $*"; }

# --- find the AXC3000's blaster by its usb serial number ----------------
USB_DIR=""
for d in /sys/bus/usb/devices/*; do
    [ -f "$d/serial" ] && [ "$(cat "$d/serial")" = "$AXC3000_SERIAL" ] && { USB_DIR=$d; break; }
done
if [ -z "$USB_DIR" ]; then
    echo "AXC3000 blaster (usb serial $AXC3000_SERIAL) is not visible in WSL." >&2
    echo "On Windows (admin PowerShell):" >&2
    echo "    usbipd list" >&2
    echo "    usbipd attach --wsl --busid <b-p>" >&2
    echo "then re-run this script." >&2
    exit 1
fi

USB_PORT=$(basename "$USB_DIR")          # e.g. 1-2, jtagconfig shows [1-2-iface0]
VID=$(cat "$USB_DIR/idVendor"); PID=$(cat "$USB_DIR/idProduct")
BUS=$(printf '%03d' "$(cat "$USB_DIR/busnum")")
DEV=$(printf '%03d' "$(cat "$USB_DIR/devnum")")
note "blaster: $VID:$PID serial $AXC3000_SERIAL  (usb $USB_PORT, bus $BUS dev $DEV)  [$(cat "$USB_DIR/product")]"

# --- --install-udev : write a persistent rule and exit --------------------
if [ "${1:-}" = "--install-udev" ]; then
    [ -n "$SUDO" ] && die "run as root: sudo $0 --install-udev"
    cat > "$UDEV_RULE" <<EOF
# Arrow AXC3000 on-board blaster (auto-generated by program.sh)
SUBSYSTEM=="usb", ATTR{idVendor}=="$VID", ATTR{idProduct}=="$PID", MODE="0666"
SUBSYSTEM=="usb", ATTR{idVendor}=="09fb", MODE="0666"
# keep ftdi_sio off the AXC3000 blaster's JTAG interface (interface 0)
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="$VID", ATTRS{idProduct}=="$PID", \\
    ATTRS{serial}=="$AXC3000_SERIAL", ATTR{bInterfaceNumber}=="00", RUN+="/bin/sh -c 'echo \$kernel > /sys/bus/usb/drivers/ftdi_sio/unbind'"
EOF
    udevadm control --reload-rules
    udevadm trigger
    echo "wrote $UDEV_RULE - replug the board (usbipd attach again) to apply."
    exit 0
fi

# --- permissions on the raw USB node -------------------------------------
$SUDO chmod 666 "/dev/bus/usb/$BUS/$DEV" 2>/dev/null || true

# --- free this blaster's interface 0 (JTAG) from the ftdi_sio driver ---
if [ -e "/sys/bus/usb/drivers/ftdi_sio/$USB_PORT:1.0" ]; then
    note "unbinding $USB_PORT:1.0 from ftdi_sio (JTAG channel)"
    echo -n "$USB_PORT:1.0" | $SUDO tee /sys/bus/usb/drivers/ftdi_sio/unbind >/dev/null 2>&1 || true
fi
# interface 1 stays as /dev/ttyUSBx - that is the UART for test_uart.py
for t in "$USB_DIR/$USB_PORT:1.1"/ttyUSB*; do
    [ -e "$t" ] && note "UART channel /dev/$(basename "$t") for: python3 ../test_uart.py --board axc3000"
done

# --- (re)start jtagd ---------------------------------------------------
pkill -x jtagd 2>/dev/null || true
sleep 1
"$QUARTUS_BIN/jtagd" 2>/dev/null || true
sleep 1

# --- show the chains, pick the cable on this blaster -------------------
JTAG="$("$QUARTUS_BIN/jtagconfig" 2>&1 || true)"
note "jtagconfig:"
echo "$JTAG"

if [ -z "${CABLE:-}" ]; then
    CABLE=$(sed -nE "s/^[0-9]+\) (.*\[$USB_PORT-iface0\])\s*$/\1/p" <<<"$JTAG")
    [ -n "$CABLE" ] || die "no jtag cable on usb $USB_PORT (serial $AXC3000_SERIAL) in jtagconfig"
fi
# the cable's chain, up to the next cable, must hold the Agilex 3
CHAIN=$(awk -v c="$CABLE" 'index($0, c) && /^[0-9]+\)/ {on=1; next} /^[0-9]+\)/ {on=0} on' <<<"$JTAG")
grep -q 'A3C' <<<"$CHAIN" || die "cable '$CABLE' has no Agilex 3 (A3C) on its chain, not the AXC3000"

if [ "${1:-}" = "--check" ]; then
    note "AXC3000 cable: $CABLE"
    exit 0
fi

# --- program --------------------------------------------------------
SOF="${1:-output_files/uart_test.sof}"
[ -f "$SOF" ] || die "sof not found: $SOF  (build it first)"

note "programming $SOF  (cable $CABLE)"
exec "$QUARTUS_BIN/quartus_pgm" -c "$CABLE" -m jtag -o "p;$SOF"
